require 'test_helper'

class NumberReadOutTest < Minitest::Test
  def test_that_it_has_a_version_number
    refute_nil ::NumberReadOut::VERSION
  end

  def test_amount_generation_gr
    tests = [
        {amount: '-1',currency: :euro,lang: :gr,result: 'ΜΕΙΟΝ ΕΝΑ ΕΥΡΩ'},
        {amount: '1',currency: :euro,lang: :gr,result: 'ΕΝΑ ΕΥΡΩ'},
        {amount: '1.01',currency: :euro,lang: :gr,result: 'ΕΝΑ ΕΥΡΩ ΚΑΙ ΕΝΑ ΕΥΡΩΛΕΠΤΟ'},
        {amount: '1.01',currency: :drachmas,lang: :gr,result: 'ΜΙΑ ΔΡΑΧΜΕΣ ΚΑΙ ΕΝΑ ΛΕΠΤΟ'},
        {amount: '10.01',currency: :euro,lang: :gr,result: 'ΔΕΚΑ ΕΥΡΩ ΚΑΙ ΕΝΑ ΕΥΡΩΛΕΠΤΟ'},
        {amount: '10.1',currency: :euro,lang: :gr,result: 'ΔΕΚΑ ΕΥΡΩ ΚΑΙ ΔΕΚΑ ΕΥΡΩΛΕΠΤΑ'},
        {amount: '10.01',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑ ΔΡΑΧΜΕΣ ΚΑΙ ΕΝΑ ΛΕΠΤΟ'},
        {amount: '10.11',currency: :euro,lang: :gr,result: 'ΔΕΚΑ ΕΥΡΩ ΚΑΙ ΕΝΤΕΚΑ ΕΥΡΩΛΕΠΤΑ'},
        {amount: '10.11',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑ ΔΡΑΧΜΕΣ ΚΑΙ ΕΝΤΕΚΑ ΛΕΠΤΑ'},
        {amount: '10.13',currency: :euro,lang: :gr,result: 'ΔΕΚΑ ΕΥΡΩ ΚΑΙ ΔΕΚΑΤΡΙΑ ΕΥΡΩΛΕΠΤΑ'},
        {amount: '10.13',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑ ΔΡΑΧΜΕΣ ΚΑΙ ΔΕΚΑΤΡΙΑ ΛΕΠΤΑ'},
        {amount: '10.21',currency: :euro,lang: :gr,result: 'ΔΕΚΑ ΕΥΡΩ ΚΑΙ ΕΙΚΟΣΙ ΕΝΑ ΕΥΡΩΛΕΠΤΑ'},
        {amount: '10.21',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑ ΔΡΑΧΜΕΣ ΚΑΙ ΕΙΚΟΣΙ ΕΝΑ ΛΕΠΤΑ'},
        {amount: '-10.21',currency: :drachmas,lang: :gr,result: 'ΜΕΙΟΝ ΔΕΚΑ ΔΡΑΧΜΕΣ ΚΑΙ ΕΙΚΟΣΙ ΕΝΑ ΛΕΠΤΑ'},
        {amount: '13.99',currency: :euro,lang: :gr,result: 'ΔΕΚΑΤΡΙΑ ΕΥΡΩ ΚΑΙ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΕΥΡΩΛΕΠΤΑ'},
        {amount: '13.99',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑΤΡΕΙΣ ΔΡΑΧΜΕΣ ΚΑΙ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΛΕΠΤΑ'},
        {amount: '1',currency: :drachmas,lang: :gr,result: 'ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '2',currency: :euro,lang: :gr,result: 'ΔΥΟ ΕΥΡΩ'},
        {amount: '3',currency: :euro,lang: :gr,result: 'ΤΡΙΑ ΕΥΡΩ'},
        {amount: '3',currency: :drachmas,lang: :gr,result: 'ΤΡΕΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '4',currency: :euro,lang: :gr,result: 'ΤΕΣΣΕΡΑ ΕΥΡΩ'},
        {amount: '4',currency: :drachmas,lang: :gr,result: 'ΤΕΣΣΕΡΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '5',currency: :euro,lang: :gr,result: 'ΠΕΝΤΕ ΕΥΡΩ'},
        {amount: '6',currency: :euro,lang: :gr,result: 'ΕΞΙ ΕΥΡΩ'},
        {amount: '7',currency: :euro,lang: :gr,result: 'ΕΠΤΑ ΕΥΡΩ'},
        {amount: '8',currency: :euro,lang: :gr,result: 'ΟΚΤΩ ΕΥΡΩ'},
        {amount: '9',currency: :euro,lang: :gr,result: 'ΕΝΝΕΑ ΕΥΡΩ'},
        {amount: '10',currency: :euro,lang: :gr,result: 'ΔΕΚΑ ΕΥΡΩ'},
        {amount: '11',currency: :euro,lang: :gr,result: 'ΕΝΤΕΚΑ ΕΥΡΩ'},
        {amount: '12',currency: :euro,lang: :gr,result: 'ΔΩΔΕΚΑ ΕΥΡΩ'},
        {amount: '13',currency: :euro,lang: :gr,result: 'ΔΕΚΑΤΡΙΑ ΕΥΡΩ'},
        {amount: '13',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑΤΡΕΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '14',currency: :euro,lang: :gr,result: 'ΔΕΚΑΤΕΣΣΕΡΑ ΕΥΡΩ'},
        {amount: '14',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑΤΕΣΣΕΡΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '15',currency: :euro,lang: :gr,result: 'ΔΕΚΑΠΕΝΤΕ ΕΥΡΩ'},
        {amount: '16',currency: :euro,lang: :gr,result: 'ΔΕΚΑΕΞΙ ΕΥΡΩ'},
        {amount: '17',currency: :euro,lang: :gr,result: 'ΔΕΚΑΕΠΤΑ ΕΥΡΩ'},
        {amount: '18',currency: :euro,lang: :gr,result: 'ΔΕΚΑΟΚΤΩ ΕΥΡΩ'},
        {amount: '19',currency: :euro,lang: :gr,result: 'ΔΕΚΑΕΝΝΕΑ ΕΥΡΩ'},
        {amount: '20',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΕΥΡΩ'},
        {amount: '21',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΕΝΑ ΕΥΡΩ'},
        {amount: '21',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '22',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΔΥΟ ΕΥΡΩ'},
        {amount: '23',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΤΡΙΑ ΕΥΡΩ'},
        {amount: '23',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΤΡΕΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '24',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΤΕΣΣΕΡΑ ΕΥΡΩ'},
        {amount: '24',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΤΕΣΣΕΡΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '25',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΠΕΝΤΕ ΕΥΡΩ'},
        {amount: '26',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΕΞΙ ΕΥΡΩ'},
        {amount: '27',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΕΠΤΑ ΕΥΡΩ'},
        {amount: '28',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΟΚΤΩ ΕΥΡΩ'},
        {amount: '29',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΕΝΝΕΑ ΕΥΡΩ'},
        {amount: '30',currency: :euro,lang: :gr,result: 'ΤΡΙΑΝΤΑ ΕΥΡΩ'},
        {amount: '40',currency: :euro,lang: :gr,result: 'ΣΑΡΑΝΤΑ ΕΥΡΩ'},
        {amount: '50',currency: :euro,lang: :gr,result: 'ΠΕΝΗΝΤΑ ΕΥΡΩ'},
        {amount: '60',currency: :euro,lang: :gr,result: 'ΕΞΗΝΤΑ ΕΥΡΩ'},
        {amount: '70',currency: :euro,lang: :gr,result: 'ΕΒΔΟΜΗΝΤΑ ΕΥΡΩ'},
        {amount: '80',currency: :euro,lang: :gr,result: 'ΟΓΔΟΝΤΑ ΕΥΡΩ'},
        {amount: '90',currency: :euro,lang: :gr,result: 'ΕΝΕΝΗΝΤΑ ΕΥΡΩ'},
        {amount: '100',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟ ΕΥΡΩ'},
        {amount: '101',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΝΑ ΕΥΡΩ'},
        {amount: '101',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟΝ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '102',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΥΟ ΕΥΡΩ'},
        {amount: '103',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΤΡΙΑ ΕΥΡΩ'},
        {amount: '103',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟΝ ΤΡΕΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '104',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΤΕΣΣΕΡΑ ΕΥΡΩ'},
        {amount: '104',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟΝ ΤΕΣΣΕΡΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '105',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΠΕΝΤΕ ΕΥΡΩ'},
        {amount: '106',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΞΙ ΕΥΡΩ'},
        {amount: '107',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΠΤΑ ΕΥΡΩ'},
        {amount: '108',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΟΚΤΩ ΕΥΡΩ'},
        {amount: '109',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΝΝΕΑ ΕΥΡΩ'},
        {amount: '110',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΕΚΑ ΕΥΡΩ'},
        {amount: '111',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΝΤΕΚΑ ΕΥΡΩ'},
        {amount: '112',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΩΔΕΚΑ ΕΥΡΩ'},
        {amount: '113',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΕΚΑΤΡΙΑ ΕΥΡΩ'},
        {amount: '113',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΕΚΑΤΡΕΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '114',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΕΚΑΤΕΣΣΕΡΑ ΕΥΡΩ'},
        {amount: '114',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΕΚΑΤΕΣΣΕΡΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '115',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΕΚΑΠΕΝΤΕ ΕΥΡΩ'},
        {amount: '116',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΕΚΑΕΞΙ ΕΥΡΩ'},
        {amount: '117',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΕΚΑΕΠΤΑ ΕΥΡΩ'},
        {amount: '118',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΕΚΑΟΚΤΩ ΕΥΡΩ'},
        {amount: '119',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΔΕΚΑΕΝΝΕΑ ΕΥΡΩ'},
        {amount: '120',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΕΥΡΩ'},
        {amount: '121',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΕΝΑ ΕΥΡΩ'},
        {amount: '121',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '122',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΔΥΟ ΕΥΡΩ'},
        {amount: '123',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΤΡΙΑ ΕΥΡΩ'},
        {amount: '123',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΤΡΕΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '124',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΤΕΣΣΕΡΑ ΕΥΡΩ'},
        {amount: '124',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΤΕΣΣΕΡΙΣ ΔΡΑΧΜΕΣ'},
        {amount: '125',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΠΕΝΤΕ ΕΥΡΩ'},
        {amount: '126',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΕΞΙ ΕΥΡΩ'},
        {amount: '127',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΕΠΤΑ ΕΥΡΩ'},
        {amount: '128',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΟΚΤΩ ΕΥΡΩ'},
        {amount: '129',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΕΝΝΕΑ ΕΥΡΩ'},
        {amount: '130',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΤΡΙΑΝΤΑ ΕΥΡΩ'},
        {amount: '140',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΣΑΡΑΝΤΑ ΕΥΡΩ'},
        {amount: '150',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΠΕΝΗΝΤΑ ΕΥΡΩ'},
        {amount: '160',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΞΗΝΤΑ ΕΥΡΩ'},
        {amount: '170',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΒΔΟΜΗΝΤΑ ΕΥΡΩ'},
        {amount: '180',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΟΓΔΟΝΤΑ ΕΥΡΩ'},
        {amount: '190',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΕΝΕΝΗΝΤΑ ΕΥΡΩ'},
        {amount: '200',currency: :euro,lang: :gr,result: 'ΔΙΑΚΟΣΙA ΕΥΡΩ'},
        {amount: '300',currency: :euro,lang: :gr,result: 'ΤΡΙΑΚΟΣΙΑ ΕΥΡΩ'},
        {amount: '400',currency: :euro,lang: :gr,result: 'ΤΕΤΡΑΚΟΣΙΑ ΕΥΡΩ'},
        {amount: '500',currency: :euro,lang: :gr,result: 'ΠΕΝΤΑΚΟΣΙΑ ΕΥΡΩ'},
        {amount: '600',currency: :euro,lang: :gr,result: 'ΕΞΑΚΟΣΙΑ ΕΥΡΩ'},
        {amount: '700',currency: :euro,lang: :gr,result: 'ΕΠΤΑΚΟΣΙΑ ΕΥΡΩ'},
        {amount: '800',currency: :euro,lang: :gr,result: 'ΟΚΤΑΚΟΣΙΑ ΕΥΡΩ'},
        {amount: '900',currency: :euro,lang: :gr,result: 'ΕΝΝΙΑΚΟΣΙΑ ΕΥΡΩ'},
        {amount: '1000',currency: :euro,lang: :gr,result: 'ΧΙΛΙΑ ΕΥΡΩ'},
        {amount: '1000',currency: :drachmas,lang: :gr,result: 'ΧΙΛΙΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '1001',currency: :euro,lang: :gr,result: 'ΧΙΛΙΑ ΕΝΑ ΕΥΡΩ'},
        {amount: '1001',currency: :drachmas,lang: :gr,result: 'ΧΙΛΙΕΣ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '2000',currency: :euro,lang: :gr,result: 'ΔΥΟ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '2000',currency: :drachmas,lang: :gr,result: 'ΔΥΟ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '3000',currency: :euro,lang: :gr,result: 'ΤΡΕΙΣ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '3000',currency: :drachmas,lang: :gr,result: 'ΤΡΕΙΣ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '4000',currency: :euro,lang: :gr,result: 'ΤΕΣΣΕΡΙΣ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '4000',currency: :drachmas,lang: :gr,result: 'ΤΕΣΣΕΡΙΣ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '5000',currency: :euro,lang: :gr,result: 'ΠΕΝΤΕ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '5000',currency: :drachmas,lang: :gr,result: 'ΠΕΝΤΕ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '6000',currency: :euro,lang: :gr,result: 'ΕΞΙ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '6000',currency: :drachmas,lang: :gr,result: 'ΕΞΙ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '7000',currency: :euro,lang: :gr,result: 'ΕΠΤΑ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '7000',currency: :drachmas,lang: :gr,result: 'ΕΠΤΑ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '8000',currency: :euro,lang: :gr,result: 'ΟΚΤΩ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '8000',currency: :drachmas,lang: :gr,result: 'ΟΚΤΩ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '9000',currency: :euro,lang: :gr,result: 'ΕΝΝΕΑ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '9000',currency: :drachmas,lang: :gr,result: 'ΕΝΝΕΑ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '10000',currency: :euro,lang: :gr,result: 'ΔΕΚΑ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '10000',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '11000',currency: :euro,lang: :gr,result: 'ΕΝΤΕΚΑ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '11000',currency: :drachmas,lang: :gr,result: 'ΕΝΤΕΚΑ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '11001',currency: :euro,lang: :gr,result: 'ΕΝΤΕΚΑ ΧΙΛΙΑΔΕΣ ΕΝΑ ΕΥΡΩ'},
        {amount: '11001',currency: :drachmas,lang: :gr,result: 'ΕΝΤΕΚΑ ΧΙΛΙΑΔΕΣ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '12000',currency: :euro,lang: :gr,result: 'ΔΩΔΕΚΑ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '12000',currency: :drachmas,lang: :gr,result: 'ΔΩΔΕΚΑ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '13000',currency: :euro,lang: :gr,result: 'ΔΕΚΑΤΡΕΙΣ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '13000',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑΤΡΕΙΣ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '14000',currency: :euro,lang: :gr,result: 'ΔΕΚΑΤΕΣΣΕΡΙΣ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '14000',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑΤΕΣΣΕΡΙΣ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '20000',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '20000',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '21000',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΜΙΑ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '21000',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΜΙΑ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '21021',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΜΙΑ ΧΙΛΙΑΔΕΣ ΕΙΚΟΣΙ ΕΝΑ ΕΥΡΩ'},
        {amount: '21021',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΜΙΑ ΧΙΛΙΑΔΕΣ ΕΙΚΟΣΙ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '21022',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΜΙΑ ΧΙΛΙΑΔΕΣ ΕΙΚΟΣΙ ΔΥΟ ΕΥΡΩ'},
        {amount: '21022',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΜΙΑ ΧΙΛΙΑΔΕΣ ΕΙΚΟΣΙ ΔΥΟ ΔΡΑΧΜΕΣ'},
        {amount: '22000',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΔΥΟ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '22000',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΔΥΟ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '23000',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΤΡΕΙΣ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '23000',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΤΡΕΙΣ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '24000',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΤΕΣΣΕΡΙΣ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '24000',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΤΕΣΣΕΡΙΣ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '25000',currency: :euro,lang: :gr,result: 'ΕΙΚΟΣΙ ΠΕΝΤΕ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '25000',currency: :drachmas,lang: :gr,result: 'ΕΙΚΟΣΙ ΠΕΝΤΕ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '100000',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '100000',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '101000',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΜΙΑ ΧΙΛΙΑΔΕΣ ΕΥΡΩ'},
        {amount: '101000',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟΝ ΜΙΑ ΧΙΛΙΑΔΕΣ ΔΡΑΧΜΕΣ'},
        {amount: '101001',currency: :euro,lang: :gr,result: 'ΕΚΑΤΟΝ ΜΙΑ ΧΙΛΙΑΔΕΣ ΕΝΑ ΕΥΡΩ'},
        {amount: '101001',currency: :drachmas,lang: :gr,result: 'ΕΚΑΤΟΝ ΜΙΑ ΧΙΛΙΑΔΕΣ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: ' - 101001',currency: :drachmas,lang: :gr,result: 'ΜΕΙΟΝ ΕΚΑΤΟΝ ΜΙΑ ΧΙΛΙΑΔΕΣ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '- 101001 ',currency: :drachmas,lang: :gr,result: 'ΜΕΙΟΝ ΕΚΑΤΟΝ ΜΙΑ ΧΙΛΙΑΔΕΣ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '1000000',currency: :euro,lang: :gr,result: 'ΕΝΑ ΕΚΑΤΟΜΥΡΙΟ ΕΥΡΩ'},
        {amount: '1000000',currency: :drachmas,lang: :gr,result: 'ΕΝΑ ΕΚΑΤΟΜΥΡΙΟ ΔΡΑΧΜΕΣ'},
        {amount: '1001001',currency: :euro,lang: :gr,result: 'ΕΝΑ ΕΚΑΤΟΜΥΡΙΟ ΧΙΛΙΑ ΕΝΑ ΕΥΡΩ'},
        {amount: '1001001',currency: :drachmas,lang: :gr,result: 'ΕΝΑ ΕΚΑΤΟΜΥΡΙΟ ΧΙΛΙΕΣ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '1101101.10',currency: :euro,lang: :gr,result: 'ΕΝΑ ΕΚΑΤΟΜΥΡΙΟ ΕΚΑΤΟΝ ΜΙΑ ΧΙΛΙΑΔΕΣ ΕΚΑΤΟΝ ΕΝΑ ΕΥΡΩ ΚΑΙ ΔΕΚΑ ΕΥΡΩΛΕΠΤΑ'},
        {amount: '1101101.10',currency: :drachmas,lang: :gr,result: 'ΕΝΑ ΕΚΑΤΟΜΥΡΙΟ ΕΚΑΤΟΝ ΜΙΑ ΧΙΛΙΑΔΕΣ ΕΚΑΤΟΝ ΜΙΑ ΔΡΑΧΜΕΣ ΚΑΙ ΔΕΚΑ ΛΕΠΤΑ'},
        {amount: '2000000',currency: :euro,lang: :gr,result: 'ΔΥΟ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '2000000',currency: :drachmas,lang: :gr,result: 'ΔΥΟ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '3000000',currency: :euro,lang: :gr,result: 'ΤΡΙΑ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '3000000',currency: :drachmas,lang: :gr,result: 'ΤΡΙΑ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '4000000',currency: :euro,lang: :gr,result: 'ΤΕΣΣΕΡΑ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '4000000',currency: :drachmas,lang: :gr,result: 'ΤΕΣΣΕΡΑ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '5000000',currency: :euro,lang: :gr,result: 'ΠΕΝΤΕ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '5000000',currency: :drachmas,lang: :gr,result: 'ΠΕΝΤΕ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '6000000',currency: :euro,lang: :gr,result: 'ΕΞΙ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '6000000',currency: :drachmas,lang: :gr,result: 'ΕΞΙ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '7000000',currency: :euro,lang: :gr,result: 'ΕΠΤΑ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '7000000',currency: :drachmas,lang: :gr,result: 'ΕΠΤΑ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '8000000',currency: :euro,lang: :gr,result: 'ΟΚΤΩ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '8000000',currency: :drachmas,lang: :gr,result: 'ΟΚΤΩ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '9000000',currency: :euro,lang: :gr,result: 'ΕΝΝΕΑ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '9000000',currency: :drachmas,lang: :gr,result: 'ΕΝΝΕΑ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '10000000',currency: :euro,lang: :gr,result: 'ΔΕΚΑ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '10000000',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '11000000',currency: :euro,lang: :gr,result: 'ΕΝΤΕΚΑ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '11000000',currency: :drachmas,lang: :gr,result: 'ΕΝΤΕΚΑ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '12000000',currency: :euro,lang: :gr,result: 'ΔΩΔΕΚΑ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '12000000',currency: :drachmas,lang: :gr,result: 'ΔΩΔΕΚΑ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '13000000',currency: :euro,lang: :gr,result: 'ΔΕΚΑΤΡΙΑ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '13000000',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑΤΡΙΑ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '14000000',currency: :euro,lang: :gr,result: 'ΔΕΚΑΤΕΣΣΕΡΑ ΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '14000000',currency: :drachmas,lang: :gr,result: 'ΔΕΚΑΤΕΣΣΕΡΑ ΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '1000000000',currency: :euro,lang: :gr,result: 'ΕΝΑ ΔΙΣΕΚΑΤΟΜΥΡΙΟ ΕΥΡΩ'},
        {amount: '1000000000',currency: :drachmas,lang: :gr,result: 'ΕΝΑ ΔΙΣΕΚΑΤΟΜΥΡΙΟ ΔΡΑΧΜΕΣ'},
        {amount: '1000001001',currency: :euro,lang: :gr,result: 'ΕΝΑ ΔΙΣΕΚΑΤΟΜΥΡΙΟ ΧΙΛΙΑ ΕΝΑ ΕΥΡΩ'},
        {amount: '1000001001',currency: :drachmas,lang: :gr,result: 'ΕΝΑ ΔΙΣΕΚΑΤΟΜΥΡΙΟ ΧΙΛΙΕΣ ΜΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '2000000000',currency: :euro,lang: :gr,result: 'ΔΥΟ ΔΙΣΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '2000000000',currency: :drachmas,lang: :gr,result: 'ΔΥΟ ΔΙΣΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '1000000000000',currency: :euro,lang: :gr,result: 'ΕΝΑ ΤΡΙΣΕΚΑΤΟΜΥΡΙΟ ΕΥΡΩ'},
        {amount: '1000000000000',currency: :drachmas,lang: :gr,result: 'ΕΝΑ ΤΡΙΣΕΚΑΤΟΜΥΡΙΟ ΔΡΑΧΜΕΣ'},
        {amount: '2000000000000',currency: :euro,lang: :gr,result: 'ΔΥΟ ΤΡΙΣΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '2000000000000',currency: :drachmas,lang: :gr,result: 'ΔΥΟ ΤΡΙΣΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '1000000000000000',currency: :euro,lang: :gr,result: 'ΕΝΑ ΤΕΤΡΑΚΙΣΕΚΑΤΟΜΥΡΙΟ ΕΥΡΩ'},
        {amount: '1000000000000000',currency: :drachmas,lang: :gr,result: 'ΕΝΑ ΤΕΤΡΑΚΙΣΕΚΑΤΟΜΥΡΙΟ ΔΡΑΧΜΕΣ'},
        {amount: '2000000000000000',currency: :euro,lang: :gr,result: 'ΔΥΟ ΤΕΤΡΑΚΙΣΕΚΑΤΟΜΥΡΙΑ ΕΥΡΩ'},
        {amount: '2000000000000000',currency: :drachmas,lang: :gr,result: 'ΔΥΟ ΤΕΤΡΑΚΙΣΕΚΑΤΟΜΥΡΙΑ ΔΡΑΧΜΕΣ'},
        {amount: '1234567890123456,12',currency: :euro,lang: :gr,result: 'ΕΝΑ ΤΕΤΡΑΚΙΣΕΚΑΤΟΜΥΡΙΟ ΔΙΑΚΟΣΙA ΤΡΙΑΝΤΑ ΤΕΣΣΕΡΑ ΤΡΙΣΕΚΑΤΟΜΥΡΙΑ ΠΕΝΤΑΚΟΣΙΑ ΕΞΗΝΤΑ ΕΠΤΑ ΔΙΣΕΚΑΤΟΜΥΡΙΑ ΟΚΤΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΚΑΤΟΜΥΡΙΑ ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΤΡΕΙΣ ΧΙΛΙΑΔΕΣ ΤΕΤΡΑΚΟΣΙΑ ΠΕΝΗΝΤΑ ΕΞΙ ΕΥΡΩ ΚΑΙ ΔΩΔΕΚΑ ΕΥΡΩΛΕΠΤΑ'},
        {amount: '1234567890123456,12',currency: :drachmas,lang: :gr,result: 'ΕΝΑ ΤΕΤΡΑΚΙΣΕΚΑΤΟΜΥΡΙΟ ΔΙΑΚΟΣΙA ΤΡΙΑΝΤΑ ΤΕΣΣΕΡΑ ΤΡΙΣΕΚΑΤΟΜΥΡΙΑ ΠΕΝΤΑΚΟΣΙΑ ΕΞΗΝΤΑ ΕΠΤΑ ΔΙΣΕΚΑΤΟΜΥΡΙΑ ΟΚΤΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΚΑΤΟΜΥΡΙΑ ΕΚΑΤΟΝ ΕΙΚΟΣΙ ΤΡΕΙΣ ΧΙΛΙΑΔΕΣ ΤΕΤΡΑΚΟΣΙEΣ ΠΕΝΗΝΤΑ ΕΞΙ ΔΡΑΧΜΕΣ ΚΑΙ ΔΩΔΕΚΑ ΛΕΠΤΑ'},
        {amount: '9999999999999999,99',currency: :euro,lang: :gr,result: 'ΕΝΝΕΑ ΤΕΤΡΑΚΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΤΡΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΔΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙEΣ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΧΙΛΙΑΔΕΣ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΕΥΡΩ ΚΑΙ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΕΥΡΩΛΕΠΤΑ'},
        {amount: '9999999999999999,99',currency: :drachmas,lang: :gr,result: 'ΕΝΝΕΑ ΤΕΤΡΑΚΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΤΡΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΔΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙEΣ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΧΙΛΙΑΔΕΣ ΕΝΝΙΑΚΟΣΙEΣ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΔΡΑΧΜΕΣ ΚΑΙ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΛΕΠΤΑ'},
        {amount: '999999999999999999,99',currency: :euro,lang: :gr,result: 'ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΤΕΤΡΑΚΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΤΡΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΔΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙEΣ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΧΙΛΙΑΔΕΣ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΕΥΡΩ ΚΑΙ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΕΥΡΩΛΕΠΤΑ'},
        {amount: '999999999999999999,99',currency: :drachmas,lang: :gr,result: 'ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΤΕΤΡΑΚΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΤΡΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΔΙΣΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙΑ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΕΚΑΤΟΜΥΡΙΑ ΕΝΝΙΑΚΟΣΙEΣ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΧΙΛΙΑΔΕΣ ΕΝΝΙΑΚΟΣΙEΣ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΔΡΑΧΜΕΣ ΚΑΙ ΕΝΕΝΗΝΤΑ ΕΝΝΕΑ ΛΕΠΤΑ'},
        {amount: '11556.8',currency: :euro,lang: :gr,result: 'ΕΝΤΕΚΑ ΧΙΛΙΑΔΕΣ ΠΕΝΤΑΚΟΣΙΑ ΠΕΝΗΝΤΑ ΕΞΙ ΕΥΡΩ ΚΑΙ ΟΓΔΟΝΤΑ ΕΥΡΩΛΕΠΤΑ'}


    ]

    tests.each do |t|
      assert_equal t[:result ],NumberReadOut.full_currency_text(t[:amount],t[:currency],t[:lang])
    end

  end

  def test_amount_generation_en
    tests = [
        {amount: '-1',currency: :euro,lang: :en,result: 'MINUS ONE EURO'},
        {amount: '1',currency: :euro,lang: :en,result: 'ONE EURO'},
        {amount: '1.01',currency: :euro,lang: :en,result: 'ONE EURO AND ONE EUROCENTS'},
        {amount: '1.01',currency: :drachmas,lang: :en,result: 'ONE DRACHMAS AND ONE CENTS'},
        {amount: '10.01',currency: :euro,lang: :en,result: 'TEN EURO AND ONE EUROCENTS'},
        {amount: '10.1',currency: :euro,lang: :en,result: 'TEN EURO AND TEN EUROCENTS'},
        {amount: '10.01',currency: :drachmas,lang: :en,result: 'TEN DRACHMAS AND ONE CENTS'},
        {amount: '1',currency: :drachmas,lang: :en,result: 'ONE DRACHMAS'},
        {amount: '2',currency: :euro,lang: :en,result: 'TWO EURO'},
        {amount: '3',currency: :euro,lang: :en,result: 'THREE EURO'},
        {amount: '4',currency: :euro,lang: :en,result: 'FOUR EURO'},
        {amount: '5',currency: :euro,lang: :en,result: 'FIVE EURO'},
        {amount: '6',currency: :euro,lang: :en,result: 'SIX EURO'},
        {amount: '7',currency: :euro,lang: :en,result: 'SEVEN EURO'},
        {amount: '8',currency: :euro,lang: :en,result: 'EIGHT EURO'},
        {amount: '9',currency: :euro,lang: :en,result: 'NINE EURO'},
        {amount: '10',currency: :euro,lang: :en,result: 'TEN EURO'},
        {amount: '11',currency: :euro,lang: :en,result: 'ELEVEN EURO'},
        {amount: '12',currency: :euro,lang: :en,result: 'TWELVE EURO'},
        {amount: '13',currency: :euro,lang: :en,result: 'THIRTEEN EURO'},
        {amount: '14',currency: :euro,lang: :en,result: 'FOURTEEN EURO'},
        {amount: '15',currency: :euro,lang: :en,result: 'FIFTEEN EURO'},
        {amount: '16',currency: :euro,lang: :en,result: 'SIXTEEN EURO'},
        {amount: '17',currency: :euro,lang: :en,result: 'SEVENTEEN EURO'},
        {amount: '18',currency: :euro,lang: :en,result: 'EIGHTEEN EURO'},
        {amount: '19',currency: :euro,lang: :en,result: 'NINETEEN EURO'},
        {amount: '20',currency: :euro,lang: :en,result: 'TWENTY EURO'},
        {amount: '21',currency: :euro,lang: :en,result: 'TWENTY-ONE EURO'},
        {amount: '22',currency: :euro,lang: :en,result: 'TWENTY-TWO EURO'},
        {amount: '23',currency: :euro,lang: :en,result: 'TWENTY-THREE EURO'},
        {amount: '24',currency: :euro,lang: :en,result: 'TWENTY-FOUR EURO'},
        {amount: '25',currency: :euro,lang: :en,result: 'TWENTY-FIVE EURO'},
        {amount: '26',currency: :euro,lang: :en,result: 'TWENTY-SIX EURO'},
        {amount: '27',currency: :euro,lang: :en,result: 'TWENTY-SEVEN EURO'},
        {amount: '28',currency: :euro,lang: :en,result: 'TWENTY-EIGHT EURO'},
        {amount: '29',currency: :euro,lang: :en,result: 'TWENTY-NINE EURO'},
        {amount: '30',currency: :euro,lang: :en,result: 'THIRTY EURO'},
        {amount: '40',currency: :euro,lang: :en,result: 'FORTY EURO'},
        {amount: '50',currency: :euro,lang: :en,result: 'FIFTY EURO'},
        {amount: '60',currency: :euro,lang: :en,result: 'SIXTY EURO'},
        {amount: '70',currency: :euro,lang: :en,result: 'SEVENTY EURO'},
        {amount: '80',currency: :euro,lang: :en,result: 'EIGHTY EURO'},
        {amount: '90',currency: :euro,lang: :en,result: 'NINETY EURO'},
        {amount: '100',currency: :euro,lang: :en,result: 'ONE HUNDRED EURO'},
        {amount: '101',currency: :euro,lang: :en,result: 'ONE HUNDRED AND ONE EURO'},
        {amount: '102',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWO EURO'},
        {amount: '103',currency: :euro,lang: :en,result: 'ONE HUNDRED AND THREE EURO'},
        {amount: '104',currency: :euro,lang: :en,result: 'ONE HUNDRED AND FOUR EURO'},
        {amount: '105',currency: :euro,lang: :en,result: 'ONE HUNDRED AND FIVE EURO'},
        {amount: '106',currency: :euro,lang: :en,result: 'ONE HUNDRED AND SIX EURO'},
        {amount: '107',currency: :euro,lang: :en,result: 'ONE HUNDRED AND SEVEN EURO'},
        {amount: '108',currency: :euro,lang: :en,result: 'ONE HUNDRED AND EIGHT EURO'},
        {amount: '109',currency: :euro,lang: :en,result: 'ONE HUNDRED AND NINE EURO'},
        {amount: '110',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TEN EURO'},
        {amount: '111',currency: :euro,lang: :en,result: 'ONE HUNDRED AND ELEVEN EURO'},
        {amount: '112',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWELVE EURO'},
        {amount: '113',currency: :euro,lang: :en,result: 'ONE HUNDRED AND THIRTEEN EURO'},
        {amount: '114',currency: :euro,lang: :en,result: 'ONE HUNDRED AND FOURTEEN EURO'},
        {amount: '115',currency: :euro,lang: :en,result: 'ONE HUNDRED AND FIFTEEN EURO'},
        {amount: '116',currency: :euro,lang: :en,result: 'ONE HUNDRED AND SIXTEEN EURO'},
        {amount: '117',currency: :euro,lang: :en,result: 'ONE HUNDRED AND SEVENTEEN EURO'},
        {amount: '118',currency: :euro,lang: :en,result: 'ONE HUNDRED AND EIGHTEEN EURO'},
        {amount: '119',currency: :euro,lang: :en,result: 'ONE HUNDRED AND NINETEEN EURO'},
        {amount: '120',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWENTY EURO'},
        {amount: '121',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWENTY-ONE EURO'},
        {amount: '122',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWENTY-TWO EURO'},
        {amount: '123',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWENTY-THREE EURO'},
        {amount: '124',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWENTY-FOUR EURO'},
        {amount: '125',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWENTY-FIVE EURO'},
        {amount: '126',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWENTY-SIX EURO'},
        {amount: '127',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWENTY-SEVEN EURO'},
        {amount: '128',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWENTY-EIGHT EURO'},
        {amount: '129',currency: :euro,lang: :en,result: 'ONE HUNDRED AND TWENTY-NINE EURO'},
        {amount: '130',currency: :euro,lang: :en,result: 'ONE HUNDRED AND THIRTY EURO'},
        {amount: '140',currency: :euro,lang: :en,result: 'ONE HUNDRED AND FORTY EURO'},
        {amount: '150',currency: :euro,lang: :en,result: 'ONE HUNDRED AND FIFTY EURO'},
        {amount: '160',currency: :euro,lang: :en,result: 'ONE HUNDRED AND SIXTY EURO'},
        {amount: '170',currency: :euro,lang: :en,result: 'ONE HUNDRED AND SEVENTY EURO'},
        {amount: '180',currency: :euro,lang: :en,result: 'ONE HUNDRED AND EIGHTY EURO'},
        {amount: '190',currency: :euro,lang: :en,result: 'ONE HUNDRED AND NINETY EURO'},
        {amount: '200',currency: :euro,lang: :en,result: 'TWO HUNDRED EURO'},
        {amount: '300',currency: :euro,lang: :en,result: 'THREE HUNDRED EURO'},
        {amount: '400',currency: :euro,lang: :en,result: 'FOUR HUNDRED EURO'},
        {amount: '500',currency: :euro,lang: :en,result: 'FIVE HUNDRED EURO'},
        {amount: '600',currency: :euro,lang: :en,result: 'SIX HUNDRED EURO'},
        {amount: '700',currency: :euro,lang: :en,result: 'SEVEN HUNDRED EURO'},
        {amount: '800',currency: :euro,lang: :en,result: 'EIGHT HUNDRED EURO'},
        {amount: '900',currency: :euro,lang: :en,result: 'NINE HUNDRED EURO'},
        {amount: '1000',currency: :euro,lang: :en,result: 'ONE THOUSAND EURO'},
        {amount: '1000',currency: :drachmas,lang: :en,result: 'ONE THOUSAND DRACHMAS'},
        {amount: '1001',currency: :euro,lang: :en,result: 'ONE THOUSAND ONE EURO'},
        {amount: '1001',currency: :drachmas,lang: :en,result: 'ONE THOUSAND ONE DRACHMAS'},
        {amount: '2000',currency: :euro,lang: :en,result: 'TWO THOUSAND EURO'},
        {amount: '10000',currency: :euro,lang: :en,result: 'TEN THOUSAND EURO'},
        {amount: '10000',currency: :drachmas,lang: :en,result: 'TEN THOUSAND DRACHMAS'},
        {amount: '11000',currency: :euro,lang: :en,result: 'ELEVEN THOUSAND EURO'},
        {amount: '11000',currency: :drachmas,lang: :en,result: 'ELEVEN THOUSAND DRACHMAS'},
        {amount: '11001',currency: :euro,lang: :en,result: 'ELEVEN THOUSAND ONE EURO'},
        {amount: '11001',currency: :drachmas,lang: :en,result: 'ELEVEN THOUSAND ONE DRACHMAS'},
       {amount: '12000',currency: :euro,lang: :en,result: 'TWELVE THOUSAND EURO'},
        {amount: '12000',currency: :drachmas,lang: :en,result: 'TWELVE THOUSAND DRACHMAS'},
        {amount: '13000',currency: :euro,lang: :en,result: 'THIRTEEN THOUSAND EURO'},
        {amount: '13000',currency: :drachmas,lang: :en,result: 'THIRTEEN THOUSAND DRACHMAS'},
        {amount: '14000',currency: :euro,lang: :en,result: 'FOURTEEN THOUSAND EURO'},
        {amount: '14000',currency: :drachmas,lang: :en,result: 'FOURTEEN THOUSAND DRACHMAS'},
        {amount: '20000',currency: :euro,lang: :en,result: 'TWENTY THOUSAND EURO'},
        {amount: '20000',currency: :drachmas,lang: :en,result: 'TWENTY THOUSAND DRACHMAS'},
        {amount: '21000',currency: :euro,lang: :en,result: 'TWENTY-ONE THOUSAND EURO'},
        {amount: '21000',currency: :drachmas,lang: :en,result: 'TWENTY-ONE THOUSAND DRACHMAS'},
        {amount: '21021',currency: :euro,lang: :en,result: 'TWENTY-ONE THOUSAND TWENTY-ONE EURO'},
        {amount: '21021',currency: :drachmas,lang: :en,result: 'TWENTY-ONE THOUSAND TWENTY-ONE DRACHMAS'},
        {amount: '21022',currency: :euro,lang: :en,result: 'TWENTY-ONE THOUSAND TWENTY-TWO EURO'},
        {amount: '21022',currency: :drachmas,lang: :en,result: 'TWENTY-ONE THOUSAND TWENTY-TWO DRACHMAS'},
        {amount: '22000',currency: :euro,lang: :en,result: 'TWENTY-TWO THOUSAND EURO'},
        {amount: '22000',currency: :drachmas,lang: :en,result: 'TWENTY-TWO THOUSAND DRACHMAS'},
        {amount: '23000',currency: :euro,lang: :en,result: 'TWENTY-THREE THOUSAND EURO'},
        {amount: '23000',currency: :drachmas,lang: :en,result: 'TWENTY-THREE THOUSAND DRACHMAS'},
        {amount: '24000',currency: :euro,lang: :en,result: 'TWENTY-FOUR THOUSAND EURO'},
        {amount: '24000',currency: :drachmas,lang: :en,result: 'TWENTY-FOUR THOUSAND DRACHMAS'},
        {amount: '25000',currency: :euro,lang: :en,result: 'TWENTY-FIVE THOUSAND EURO'},
        {amount: '25000',currency: :drachmas,lang: :en,result: 'TWENTY-FIVE THOUSAND DRACHMAS'},
        {amount: '100000',currency: :euro,lang: :en,result: 'ONE HUNDRED THOUSAND EURO'},
        {amount: '100000',currency: :drachmas,lang: :en,result: 'ONE HUNDRED THOUSAND DRACHMAS'},
        {amount: '101000',currency: :euro,lang: :en,result: 'ONE HUNDRED AND ONE THOUSAND EURO'},
        {amount: '101000',currency: :drachmas,lang: :en,result: 'ONE HUNDRED AND ONE THOUSAND DRACHMAS'},
        {amount: '101001',currency: :euro,lang: :en,result: 'ONE HUNDRED AND ONE THOUSAND ONE EURO'},
        {amount: '101001',currency: :drachmas,lang: :en,result: 'ONE HUNDRED AND ONE THOUSAND ONE DRACHMAS'},
        {amount: '1000000',currency: :euro,lang: :en,result: 'ONE MILLION EURO'},
        {amount: '1000000',currency: :drachmas,lang: :en,result: 'ONE MILLION DRACHMAS'},
        {amount: '1001001',currency: :euro,lang: :en,result: 'ONE MILLION ONE THOUSAND ONE EURO'},
        {amount: '1001001',currency: :drachmas,lang: :en,result: 'ONE MILLION ONE THOUSAND ONE DRACHMAS'},
        {amount: '1000000',currency: :euro,lang: :en,result: 'ONE MILLION EURO'},
        {amount: '2000000',currency: :euro,lang: :en,result: 'TWO MILLION EURO'},
        {amount: '1101101.10',currency: :euro,lang: :en,result: 'ONE MILLION ONE HUNDRED AND ONE THOUSAND ONE HUNDRED AND ONE EURO AND TEN EUROCENTS'},
        {amount: '1101101.10',currency: :drachmas,lang: :en,result: 'ONE MILLION ONE HUNDRED AND ONE THOUSAND ONE HUNDRED AND ONE DRACHMAS AND TEN CENTS'},
        {amount: '10000000',currency: :euro,lang: :en,result: 'TEN MILLION EURO'},
        {amount: '10000000',currency: :drachmas,lang: :en,result: 'TEN MILLION DRACHMAS'},
        {amount: '11000000',currency: :euro,lang: :en,result: 'ELEVEN MILLION EURO'},
        {amount: '11000000',currency: :drachmas,lang: :en,result: 'ELEVEN MILLION DRACHMAS'},
        {amount: '12000000',currency: :euro,lang: :en,result: 'TWELVE MILLION EURO'},
        {amount: '12000000',currency: :drachmas,lang: :en,result: 'TWELVE MILLION DRACHMAS'},
        {amount: '13000000',currency: :euro,lang: :en,result: 'THIRTEEN MILLION EURO'},
        {amount: '13000000',currency: :drachmas,lang: :en,result: 'THIRTEEN MILLION DRACHMAS'},
        {amount: '14000000',currency: :euro,lang: :en,result: 'FOURTEEN MILLION EURO'},
        {amount: '14000000',currency: :drachmas,lang: :en,result: 'FOURTEEN MILLION DRACHMAS'},
        {amount: '1000000000',currency: :euro,lang: :en,result: 'ONE BILLION EURO'},
        {amount: '2000000000',currency: :euro,lang: :en,result: 'TWO BILLION EURO'},
        {amount: '1000000000',currency: :drachmas,lang: :en,result: 'ONE BILLION DRACHMAS'},
        {amount: '1000001001',currency: :euro,lang: :en,result: 'ONE BILLION ONE THOUSAND ONE EURO'},
        {amount: '1000001001',currency: :drachmas,lang: :en,result: 'ONE BILLION ONE THOUSAND ONE DRACHMAS'},
        {amount: '2000000000',currency: :euro,lang: :en,result: 'TWO BILLION EURO'},
        {amount: '2000000000',currency: :drachmas,lang: :en,result: 'TWO BILLION DRACHMAS'},
        {amount: '1000000000000',currency: :euro,lang: :en,result: 'ONE TRILLION EURO'},
        {amount: '1000000000000',currency: :drachmas,lang: :en,result: 'ONE TRILLION DRACHMAS'},
        {amount: '1000000000000',currency: :euro,lang: :en,result: 'ONE TRILLION EURO'},
        {amount: '2000000000000',currency: :euro,lang: :en,result: 'TWO TRILLION EURO'},
        {amount: '1000000000000000',currency: :euro,lang: :en,result: 'ONE QUADRILLION EURO'},
        {amount: '2000000000000000',currency: :euro,lang: :en,result: 'TWO QUADRILLION EURO'},
        {amount: '1234567890123456,12',currency: :euro,lang: :en,result: 'ONE QUADRILLION TWO HUNDRED AND THIRTY-FOUR TRILLION FIVE HUNDRED AND SIXTY-SEVEN BILLION EIGHT HUNDRED AND NINETY MILLION ONE HUNDRED AND TWENTY-THREE THOUSAND FOUR HUNDRED AND FIFTY-SIX EURO AND TWELVE EUROCENTS'},
        {amount: '9999999999999999,99',currency: :euro,lang: :en,result: 'NINE QUADRILLION NINE HUNDRED AND NINETY-NINE TRILLION NINE HUNDRED AND NINETY-NINE BILLION NINE HUNDRED AND NINETY-NINE MILLION NINE HUNDRED AND NINETY-NINE THOUSAND NINE HUNDRED AND NINETY-NINE EURO AND NINETY-NINE EUROCENTS'},
        {amount: '999999999999999999,99',currency: :euro,lang: :en,result: 'NINE HUNDRED AND NINETY-NINE QUADRILLION NINE HUNDRED AND NINETY-NINE TRILLION NINE HUNDRED AND NINETY-NINE BILLION NINE HUNDRED AND NINETY-NINE MILLION NINE HUNDRED AND NINETY-NINE THOUSAND NINE HUNDRED AND NINETY-NINE EURO AND NINETY-NINE EUROCENTS'},
        {amount: '11556.8',currency: :euro,lang: :en,result: 'ELEVEN THOUSAND FIVE HUNDRED AND FIFTY-SIX EURO AND EIGHTY EUROCENTS'}

    ]

    tests.each do |t|

      assert_equal t[:result ],NumberReadOut.full_currency_text(t[:amount],t[:currency],t[:lang])

    end

  end

end
